name = "worker"
type = "webpack"

account_id = "18fee802749992d5fac53a9656f63cd5"
workers_dev = true
compatibility_date = "2021-10-28"

kv_namespaces = [
    { binding = "posts", preview_id = "f911e9a597e14a7f9fa9250f0a3490bd", id = "8cbdff31b21c45ab9c8a268f445952ea" },
]
